import { Inria_Sans } from "next/font/google";
import "./globals.css";

const inriaSans = Inria_Sans({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inriaSans.className}>{children}</body>
    </html>
  );
}
